[package]
name = "blockchain-core"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
k256 = { version = "0.13", features = ["ecdsa"] }
serde_json = "1.0"
hex = "0.4"